spring:
  application:
    name: yuchuang
  session:
    store-type: redis
    timeout: 259200
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuchuang?useUnicode=true&characterEncoding=utf-8&useInformationSchema=true
    username: root
    password: 1234
  profiles:
    active: local
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
      database: 0
#      username: root
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 259200
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yadong.yuchuang.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志打印级别设置
logging:
  level:
    root: INFO

# 对象存储配置
cos:
  client:
    host: cos.ap-guangzhou.myqcloud.com
    secretId: <Your SecretId>
    secretKey: <Your SecretKey>
    region: ap-guangzhou
    bucket: <Your BucketName>

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
